"""Public council persistence boundary; one unit of work per atomic change."""
from contextlib import AbstractContextManager
from typing import Any, Protocol
from uuid import UUID


class CouncilRepository(Protocol):
    @property
    def in_transaction(self) -> bool: ...
    def transaction(self, *, write: bool = True) -> AbstractContextManager: ...
    def require_revision(self, debate_id: UUID, revision: int) -> Any: ...
    def current_round(self, debate_id: UUID) -> Any: ...
    def round_spec(self, round_id: UUID) -> Any: ...
    def binding(self, debate_id: UUID, participant_id: UUID) -> Any: ...
    def wait_state(self, debate_id: UUID) -> str: ...
    def slot_exists(self, round_id: UUID, participant_id: UUID) -> bool: ...
    def has_review(self, debate_id: UUID) -> bool: ...
    def set_wait_state(self, debate_id: UUID, state: str) -> None: ...
    def put(self, kind: str, record: Any, revision: int, event_kind: str, record_id: UUID) -> Any: ...
    def advance(self, debate_id: UUID, revision: int, kind: str, payload: dict) -> Any: ...
    def register_synthesis(self, spec: Any) -> None: ...
    def require_round_confirmed(self, debate_id: UUID, round_id: UUID) -> None: ...
    def record_and_events(self, kind: str, round_id: UUID, event_kind: str) -> Any: ...
    def entries(self, debate_id: UUID | None = None) -> Any: ...
    def marked_events(self) -> Any: ...
    def debate_states(self) -> Any: ...
    def has_final(self, debate_id: UUID) -> bool: ...
